[package]
name = "swat-resolver"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
swat-core = { path = "../swat-core" }
swat-store = { path = "../swat-store" }
swat-value = { path = "../swat-value" }

[dev-dependencies]
swat-adapter-agent = { path = "../swat-adapter-agent" }
swat-session = { path = "../swat-session" }
