[package]
name = "swat-ui-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
crossterm.workspace = true
ratatui.workspace = true
swat-adapter-agent = { path = "../swat-adapter-agent" }
swat-adapter-local = { path = "../swat-adapter-local" }
swat-adapter-mock = { path = "../swat-adapter-mock" }
swat-adapter-pcgeos = { path = "../swat-adapter-pcgeos" }
swat-api = { path = "../swat-api" }
swat-command = { path = "../swat-command" }
swat-control = { path = "../swat-control" }
swat-core = { path = "../swat-core" }
swat-expr = { path = "../swat-expr" }
swat-session = { path = "../swat-session" }
swat-source = { path = "../swat-source" }
swat-store = { path = "../swat-store" }
swat-value = { path = "../swat-value" }

[dev-dependencies]
